version: '3'
services:
  app:
    build: .
    network_mode: "host"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - BROWSER=none
      - HOST=0.0.0.0
      - REACT_APP_DISABLE_TELEMETRY=true
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
